version: '3.8'
services: 
  dev-database: 
    image: postgres:15.0
    container_name: dev-database
    ports: 
    - 5432:5432
  enviroment: 
    POSTGRES_USER: postges
    POSTGRES_PASSWORD: Abc123456789
    POSTGRES_DB: testdb
  networks:
    - nestjs-network
networks:
  nestjs-network:
# Create container, network, ... from "docker composer" file: 
# -d: deamon/background mode
# docker compose up -d